export enum MeasurementDatabases {
    "Engine rates per minute" = 'obd.rpm',
    "Acceleration" = "acc.xyz",
    "Transversal Acceleration" = "obd.acc_trans",
    "Longitudal Acceleration" = "obd.acc_long",
    "Yaw rate" = "obd.acc_yaw",
    "Electric brake torque" = "obd.brk_trq_req_el",
    "Driver brake torque" = "obd.brk_trq_req_dvr",
    
    "Steering Position" = 'obd.strg_pos' ,
    "Steering Acceleration"  =  "obd.strg_acc" ,
    "Steering WheelAngle Offset " =  "obd.strg_ang" ,
     "Estimated Wheel Torque " =  "obd.whl_trq_est " ,
     "DriverBrakeWheelTq_Req" =  "obd.brk_trq_req_dvr " ,
     "ElecBrakeWheelsTorqueReques" =  "obd.brk_trq_req_elec " ,
     "MeanEffectiveTorque" =  "obd.trq_eff" ,
    "RequestedTorqueAfterProc " = 'obd.trq_req' ,
    "TotalPotentialResistiveWheelsTorque"  =  "obd.whl_trq_pot_ri " ,
    "ElecBrakeWheelsTorqueApplied" =  "obd.brk_trq_elec" ,
     "ElecEngineRPM" =  "obd.rpm_elec" ,
     "ASR Dynamic Torque Request" =  "obd.asr_trq_req_dyn" ,
     "ASR Static Torque Request" =  "obd.asr_trq_req_st" ,
     "MSR Torque Request" =  "obd.msr_trq_req" ,
    "Rpm Front Right" = 'obd.rpm_fr' ,
    "Rpm Front Left"  =  "obd.rpm_fl" ,
    "Vehicle Speed" =  "obd.spd_veh" ,
     "Rpm Rear Right" =  "obd.rpm_rr" ,
     "Rpm Rear Left" =  "obd.rpm_rl" ,
     "Speed" =  "obd.spd" ,
     "Odometer" =  "obd.odo" ,
    "Fine distance"  =  "obd.f_dist" ,
    "Front Wiping Request" =  "obd.ww_f_req" ,
     "Traction Instant Consumption" =  "obd.trac_cons" ,
     "Average trip B consumpion" =  "obd.trip_cons_avg" ,
     "Trip B distance" =  "obd.trip_dist" ,
     "trip B consumption" =  "obd.trip_cons" ,
    "Average trip B speed" = 'obd.trip_spd_avg' ,
    "Driver Safety Belt Reminder"  =  "obd.sb_rem_fl" ,
    "Front Passenger Safety Belt Reminder" =  "obd.sb_rem_fr" ,
     "Second Row Center Safety Belt State" =  "obd.sb_stat_rc" ,
     "Second Row Left Safety Belt State" =  "obd.sb_stat_rl" ,
     "Second Row Right Safety Belt State" =  "obd.sb_stat_rr" ,
     "Average Consumption" =  "obd.cons_avg" ,
    "External Temp"  =  "obd.temp_ext" ,
    "Rear right wheel pressure" =  "obd.whl_prs_rr" ,
     "Rear left wheel pressure" =  "obd.whl_prs_rl" ,
     "Front right wheel pressure" =  "obd.whl_prs_fr" ,
     "Front left wheel pressure" =  "obd.whl_prs_fl" ,
     "Temperature" =  "obd.temp" ,
    "Local Time" = 'obd.time' ,
    "Front Wiper Stop Position"  =  "obd.ww_f_stat" ,
    "Front Wiper Status" =  "obd.ww_f_stop" 
}

export const MeasurementsArray = [
    {label:"Engine rates per minute", value:'obd.rpm'},
    {label:"Acceleration" , value: "acc.xyz"},
    {label:"Transversal Acceleration", value: "obd.acc_trans"},
    {label: "Longitudal Acceleration", value: "obd.acc_long"},
    {label: "Yaw rate", value: "obd.acc_yaw"},
    {label: "Electric brake torque", value: "obd.brk_trq_req_el"},
    {label: "Driver brake torque", value: "obd.brk_trq_req_dvr"},
    {label:"Steering Position", value:'obd.strg_pos'},
    {label:"Steering Acceleration" , value: "obd.strg_acc"},
    {label:"Steering WheelAngle Offset ", value: "obd.strg_ang"},
    {label: "Estimated Wheel Torque ", value: "obd.whl_trq_est "},
    {label: "DriverBrakeWheelTq_Req", value: "obd.brk_trq_req_dvr "},
    {label: "ElecBrakeWheelsTorqueReques", value: "obd.brk_trq_req_elec "},
    {label: "MeanEffectiveTorque", value: "obd.trq_eff"},
    {label:"RequestedTorqueAfterProc ", value:'obd.trq_req'},
    {label:"TotalPotentialResistiveWheelsTorque" , value: "obd.whl_trq_pot_ri "},
    {label:"ElecBrakeWheelsTorqueApplied", value: "obd.brk_trq_elec"},
    {label: "ElecEngineRPM", value: "obd.rpm_elec"},
    {label: "ASR Dynamic Torque Request", value: "obd.asr_trq_req_dyn"},
    {label: "ASR Static Torque Request", value: "obd.asr_trq_req_st"},
    {label: "MSR Torque Request", value: "obd.msr_trq_req"},
    {label:"Rpm Front Right", value:'obd.rpm_fr'},
    {label:"Rpm Front Left" , value: "obd.rpm_fl"},
    {label:"Vehicle Speed", value: "obd.spd_veh"},
    {label: "Rpm Rear Right", value: "obd.rpm_rr"},
    {label: "Rpm Rear Left", value: "obd.rpm_rl"},
    {label: "Speed", value: "obd.spd"},
    {label: "Odometer", value: "obd.odo"},
    {label:"Fine distance" , value: "obd.f_dist"},
    {label:"Front Wiping Request", value: "obd.ww_f_req"},
    {label: "Traction Instant Consumption", value: "obd.trac_cons"},
    {label: "Average trip B consumpion", value: "obd.trip_cons_avg"},
    {label: "Trip B distance", value: "obd.trip_dist"},
    {label: "trip B consumption", value: "obd.trip_cons"},
    {label:"Average trip B speed", value:'obd.trip_spd_avg'},
    {label:"Driver Safety Belt Reminder" , value: "obd.sb_rem_fl"},
    {label:"Front Passenger Safety Belt Reminder", value: "obd.sb_rem_fr"},
    {label: "Second Row Center Safety Belt State", value: "obd.sb_stat_rc"},
    {label: "Second Row Left Safety Belt State", value: "obd.sb_stat_rl"},
    {label: "Second Row Right Safety Belt State", value: "obd.sb_stat_rr"},
    {label: "Average Consumption", value: "obd.cons_avg"},
    {label:"External Temp" , value: "obd.temp_ext"},
    {label:"Rear right wheel pressure", value: "obd.whl_prs_rr"},
    {label: "Rear left wheel pressure", value: "obd.whl_prs_rl"},
    {label: "Front right wheel pressure", value: "obd.whl_prs_fr"},
    {label: "Front left wheel pressure", value: "obd.whl_prs_fl"},
    {label: "Temperature", value: "obd.temp"},
    {label:"Local Time", value:'obd.time'},
    {label:"Front Wiper Stop Position" , value: "obd.ww_f_stat"},
    {label:"Front Wiper Status", value: "obd.ww_f_stop"}
]

